# Generated by Django 3.0.7 on 2020-09-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_cargo_closed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='cargo',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
